<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Deterministic>true</Deterministic>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <AnalysisLevel>latest</AnalysisLevel>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>portable</DebugType>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>

        <Company>Nodsoft Systems</Company>
        <Authors>Sakura Akeno Isayeki</Authors>
        <Title>PostgreSQL Backplane for SignalR Core</Title>
        <Product>PostgreSQL Backplane for SignalR Core</Product>
        <Description>A PostgreSQL backplane for ASP.NET Core SignalR, enabling real-time communication across multiple servers/instances.</Description>
        <RepositoryUrl>https://github.com/Nodsoft/SignalR.PostgreSQL</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <CommonPackageTags>aspnetcore, signalr, postgres, backplane</CommonPackageTags>
        <PackageTags>$(CommonPackageTags)</PackageTags> <!-- Default package tags -->

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <!-- Nerdbank.GitVersioning -->
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="$(PackAsTool) != 'true'">
        <PackageReference Include="DotNet.ReproducibleBuilds" Version="2.0.2" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup Label="PackageInfoFiles">
        <!-- Import the Readme at build props level if there is none in the project -->

        <None Condition="!Exists('README.md')" Include="$(_DirectoryBuildPropsBasePath)\README.md" Pack="true" PackagePath="/" />
        <None Include="$(MSBuildThisFileDirectory)\LICENSE" Pack="true" PackagePath="/" />
        <None Condition="!Exists('icon.png')" Include="$(MSBuildThisFileDirectory)\icon.png" Pack="true" PackagePath="/" />
    </ItemGroup>
    
</Project>